FROM  docker.senthink.com/repository/senthink/php:7-apache
COPY . /var/www/html
RUN chmod -R 755 /var/www/html
VOLUME /var/www/html
COPY laravel-scheduler /etc/cron.d/
RUN chmod 0644 /etc/cron.d/laravel-scheduler
RUN chown -R www-data:www-data /var/www/html/storage
RUN chown -R www-data:www-data /var/www/html/bootstrap/cache
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
EXPOSE 80